apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  labels:
    app: boardgame
spec:
  type: LoadBalancer
  selector:
    app: boardgame
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
